### PR TITLE
enable clang analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by yetist** [comment]
@raveit65 

I need you, please enable `gh-pages` for pages.

**Comment by raveit65** [comment]
@yetist 
Done.

**Comment by sc0w** [comment]
@yetist I can't see the warnings in the logs in master

for example, deprecated functions

**Comment by yetist** [comment]
It seems lost the 'build_scripts' section in '.travis.yml' file.

**Comment by sc0w** [comment]
thanks!

fixed with https://github.com/mate-desktop/eom/commit/0de1436ca6e8926675f8d0cc75eae7d8331e7b9d

**Pull request merged**
