### PR TITLE
fix translations merge issue during build

### PR DESCRIPTION
**Pull request by NiceandGently**
not shure if this is the right place to fix the syntax errors, maybe this should be done at transiflex.

### CODE REVIEW

**Comment by NiceandGently** [comment]
@stefano-k 
@flexiondotorg 
I don't have any rights to do that at transiflex for this languages.

**Comment by stefano-k** [comment]
@cardpuncher can you take a look?

**Comment by cardpuncher** [comment]
Stefano Karapetsas wrote:
> @cardpuncher <https://github.com/cardpuncher> can you take a look?

Hm, I searched on 
<https://www.transifex.com/projects/p/MATE/viewstrings/#fi/eom/2607323> 
but there are no occurrences of "eom-open-image" or of its variants. The 
same is also true for Korean 
(<https://www.transifex.com/projects/p/MATE/viewstrings/#ko/eom?q=guilab> returns 
no results).

BTW, the files in question look like help files. Sorry for the awkward 
question, but do we already have them on Transifex?

**Comment by NiceandGently** [comment]
ok, looks like we have the same prob here
https://github.com/NiceandGently/pluma/commit/d91a7ae190d91161bb32def8e48e9cc98973d9d8
@clefebvre told me that those entries aren't at french translation for pluma.
@cardpuncher  can you check this please?
And yes those are all help files. I stumbled about that during compile warnings.
But for example i don't see any warning about ' could not merge' during compile with other languages.
@stefano-k 
What do you think?

**Comment by cardpuncher** [comment]
No_name wrote:
> ok, looks like we have the same prob here
> NiceandGently/pluma@d91a7ae
> <https://github.com/NiceandGently/pluma/commit/d91a7ae190d91161bb32def8e48e9cc98973d9d8>
> @clefebvre <https://github.com/clefebvre> told me that those entries
> aren't at french translation for pluma.
> @cardpuncher <https://github.com/cardpuncher> can you check this please?

Done and I can confirm what Clément said: those entries are absent from 
the French translation of Pluma on Transifex, certainly because the help 
files aren't on Transifex.

**Comment by NiceandGently** [comment]
@cardpuncher 
@stefano-k 
So we can savely merge this PR here, to avoid a override from transiflex?
I ask to be shure of this.

**Comment by cardpuncher** [comment]
No_name wrote:
> @cardpuncher <https://github.com/cardpuncher>
> @stefano-k <https://github.com/stefano-k>
> So we can savely merge this PR here, to avoid a override from transiflex?

As these files aren't on Transifex, translators can't make updates that 
could override your changes. That being said, if I were you I'd beat 
Stefano into a pulp until he confirms that :)

**Pull request merged**
