### PR TITLE
Upgrade ui files

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Buttons on `eom-image-properties-dialog.ui` are looking different.
Before:
eom-1
With PR:
eom-1-new

I am still wondering how open the `eom-multiple-save-as-dialog.ui` dialog?

**Comment by rbuj** [comment]
> I am still wondering how open the `eom-multiple-save-as-dialog.ui` dialog?

Select several picture on Side Pane, next click on save as..

Screenshot at 2020-12-29 16-15-16

**Comment by raveit65** [comment]
Honestly, i never saw this dialog wich comes up now with latest commit at master, good.
Did you fixed the button layout of `eom-image-properties-dialog.ui` with latest force-push?

**Comment by rbuj** [comment]
> Honestly, i never saw this dialog wich comes up now with latest commit at master, good.
> Did you fixed the button layout of `eom-image-properties-dialog.ui` with latest force-push?

The issue is not related to the layout, it's about i18n/l10n and resources.

**Comment by raveit65** [comment]
You can use `layout-style= GTK_BUTTONBOX_EDGE` to fix that.
Bildschirmfoto zu 2020-12-29 17-51-10

**Comment by rbuj** [comment]
@raveit65 I think it's fixed now.

**Comment by raveit65** [comment]
Your're right `layout-style= GTK_BUTTONBOX_END` was used before.
The translation issue (different meaning of button text) is fixed by last commit.
Thanks

**Review by raveit65 — APPROVED** [review]
Works for me.

**Pull request merged**
