### PR TITLE
Sidebar finishing

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
Note, the first 2 commits are needed for google drive.
This was written in gnome bugreport..

**Comment by vkareh** [comment]
@raveit65 - how do you test the google drive stuff?

**Comment by lukefromdc** [comment]
Someone here who has a Google account and/or is willing to deal with Google should test the Google Drive stuff.

**Comment by monsta** [comment]
Looks like it tries to get the "display name" via `g_file_info_get_display_name`, if it fails, it falls back to `g_file_get_basename` that was in the code before that commit. Maybe it can be tested without Google Drive.

**Comment by raveit65** [comment]
I use some other cloud provider which provide webdav links to the cloud.
Those links i can use with the connect-to-server-dialog from caja and i have a folder from my cloud in caja.
I am not sure if google-drive support webdav, as i avoid to use google service to protect my privacy.
Any way, it should be fine if you can open the containing folder with caja.
And i trust the origin commit from gtk+ dev for eog
https://gitlab.gnome.org/GNOME/eog/commit/fff55c6afdd1c159c1ec554316fa6170f561cbe1
and the description about gvfs in report.
https://bugzilla.gnome.org/show_bug.cgi?id=754731#c0
If you think this is insecure i can drop those commits, but i thought it would be useful for google-drive users.

**Comment by lukefromdc** [comment]
It could only be insecure if it contains code to connect to a cloud provider by default. According to the linked reports, the backend is in GVFS, all we are doing is changing some names to suit it

**Pull request merged**
