### PR TITLE
svg: Fix offset coordinates when transforming SVG images on HiDPI displays

### PR DESCRIPTION
**Pull request by vkareh**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Note that I am testing with window-scaling=2 on a small screen if it makes any difference, and don't have any SVG images around larger than the smallest EOM window

**Comment by raveit65** [comment]
Opps, i can reproduce the issue with HIDPI monitor.
eom-svg

**Comment by vkareh** [comment]
Is that with or without the patch?

**Comment by raveit65** [comment]
Don't worry, with PR it looks well :)
eom-svg-good

**Pull request merged**
