### PR TITLE
open image in filebrowser and improvement for properties-dialog

### PR DESCRIPTION
**Pull request by raveit65**
Please test

### CODE REVIEW

**Comment by lukefromdc** [comment]
I do get this warning on opening the containing folder:
`
** (caja:21027): CRITICAL **: 15:17:35.644: caja_file_unref: assertion 'CAJA_IS_FILE (file)' failed
`

**Comment by raveit65** [comment]
Where do you see this error message?
I don't see that in a terminal with an open **eom** process if choosing the new menu entry.

**Comment by raveit65** [comment]
After reading eom report https://bugzilla.gnome.org/show_bug.cgi?id=650402 i checked that we have the API from nautilus https://gitlab.gnome.org/GNOME/nautilus/commit/6ed0cae9df696b816309b6c6d8fdb2660c66b922
The freedesktop interface is still there in caja code. 
https://github.com/mate-desktop/caja/blob/master/data/freedesktop-dbus-interfaces.xml
So, it should be fine to add the `open-containing-folder` command in general.

But i am still wondering where do you see that warning, i retested it.

**Comment by lukefromdc** [comment]
The warning comes up on "open containing folder" as soon as Caja opens. It appears not in a terminal running EOM but rather a terminal running Caja. Found it while investigating crashes on closing caja windows  with GTK 3.23.0 that turned out to come from a python-caja problem with this new GTK version.

**Comment by lukefromdc** [comment]
Easy way to test is "sudo caja" from terminal any folder containing images, then open one in EOM from that folder (will be as root), and select "open containing folder"  at which point the terminal running "sudo caja" will show the warning. Otherwise you need to remove caja from session->required components and start a new session with caja running from terminal to see it.

**Comment by raveit65** [comment]
I don't get this warning here.
With caja disabled from from session start and using caja -n or caja as command in terminal.
```
[rave@mother ~]$ caja -n
Initializing caja-dropbox 1.20.0
Initializing caja-image-converter extension
Initializing caja-open-terminal extension
Initializing caja-xattr-tags extension
^C
[rave@mother ~]$ caja
Initializing caja-dropbox 1.20.0
Initializing caja-image-converter extension
Initializing caja-open-terminal extension
Initializing caja-xattr-tags extension

```
With starting caja and eom as root
```
[rave@mother ~]$ su
Passwort: 
[root@mother rave]# caja

(caja:28559): GLib-GIO-CRITICAL **: 09:17:38.567: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Initializing caja-dropbox 1.20.0
Initializing caja-image-converter extension
Initializing caja-open-terminal extension
Initializing caja-xattr-tags extension
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)


[rave@mother ~]$ su
Passwort: 
[root@mother rave]# eom

(eom:27838): EOM-WARNING **: 09:06:31.507: Service registration failed.

** (eom:27838): WARNING **: 09:06:31.507: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(eom:27838): dconf-WARNING **: 09:06:31.598: failed to commit changes to dconf: Verbindung ist geschlossen

(eom:27838): dconf-WARNING **: 09:06:31.598: failed to commit changes to dconf: Verbindung ist geschlossen

(eom:27838): dconf-WARNING **: 09:06:31.601: failed to commit changes to dconf: Verbindung ist geschlossen

(eom:27838): dconf-WARNING **: 09:06:31.601: failed to commit changes to dconf: Verbindung ist geschlossen


**now, opening containing folder**

(caja:27844): GLib-GIO-CRITICAL **: 09:07:12.519: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Initializing caja-dropbox 1.20.0
Initializing caja-image-converter extension
Initializing caja-open-terminal extension
Initializing caja-xattr-tags extension
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)
Error creating proxy: Verbindung ist geschlossen (g-io-error-quark, 18)

```
I see only old well known warnings if you start caja as root.

Can someone other from team test this please?

**Comment by raveit65** [comment]
Same if i open an image from a folder inside a root caja with eom, i don't see that warning in terminal where i started 'sudo caja'.
Do you run caja in debug mode?

**Comment by raveit65** [comment]
Problem with python2/3 migration in you distro?
Installing python-caja doesn't generate this warning here, but you need a python caja extension installed.
Normal i don't have python2-caja installed anymore as there is no extension which i use for my own.
Btw. it is possible to build python-caja with python3, see https://src.fedoraproject.org/rpms/python-caja/pull-request/2

**Comment by raveit65** [comment]
And yes, it doesn't opens the caja window in foreground. Maybe there is commit for it i later eog development.
But my goal was to enable the eom sidebar (see other branches) which provides a button for the open-containing-folder command, so i didn't search for it.
Btw.  With `Enable more Drag&Drop actions when eog is drag source` commit you can generate a symlink in caja if you press `crtl+shift` during drag&drop an image from eom to caja.
See https://bugzilla.gnome.org/show_bug.cgi?id=667076
(Opps, i need to rename commit :smile:  )

**Pull request merged**
