### PR TITLE
Scale HiDPI images correctly

### PR DESCRIPTION
**Pull request by vkareh**

### CODE REVIEW

**Comment by vkareh** [comment]
Without this patch, opening a file when scale=2 results in an image that is twice as large as its reported size when zooming to normal size.

**Comment by raveit65** [comment]
Same here.
A screenshot from my desktop with (3840px x 2140px) doesn't match my monitor size (3840 x 2140) in full screen mode if using orginal size.

**Comment by lukefromdc** [comment]
Question: Is this supposed to make "zoom normal" zoom the image to its size in real pixels or to its size in pixels multiplied by the window scale factor? The latter is what I get here, no idea what if anything I am doing wrong. Screen is 1920x1080, the largest I have. I used a small image for testing, one that filled about half my desktop height when scaled and about a quarter of it natively

**Comment by vkareh** [comment]
@lukefromdc - it's supposed to zoom to its size in real pixels, so if your screen is 1920x1080, and the image is 1920x1080, zoom normal should fill the screen 1:1 (you might end up with a scrollbar due to panels and window decorations, but it should be the same size).

a 960x540 image should fill a quarter of the screen for a 1920x1080 display, regardless of your scale value

**Comment by lukefromdc** [comment]
That is NOT the results I got, I got it zoomed in scaled pixels instead so at window-scaling = 2 the image was double-sized

**Comment by vkareh** [comment]
ah, I see - yeah that was the behavior I got from eom before this patch. What happens on your eom _without_ this patch? (also, did you restart eom?)

**Comment by lukefromdc** [comment]
I was careful to ensure a clean restart (no files open in eom) for each test, and the results I got were the same with master and with this PR

**Comment by raveit65** [comment]
So, is this a problem with master and the PR doesn't change the behaviour for you?
Or does the PR create a bug for you with non-hidipi monitors?
I ask because i have push this already to fedora builds as it fixes the behaviour with HIDPI for me.

**Comment by lukefromdc** [comment]
No new bug, issue same in master and with this PR. I might be doing something wrong so feel free to use this anyway.

**Pull request merged**
