### PR TITLE
GTK3: reduce size of the statusbar

### PR DESCRIPTION
**Pull request by NiceandGently**
- extra resize code is useless since gtk+ handle it
- Use a simple GtkLabel for the image counter in the statusbar
This was an extra GtkStatusbar before. This is not needed anymore as the
resize handle now works independently from the GtkStatusbar.
- set margin of statusbar to zero

### CODE REVIEW

**Comment by monsta** [comment]
Works fine for me in Debian Testing, but... enabling "Date in statusbar" plugin makes the statusbar too tall again (only in GTK+3 build).

**Note**: it happens only when the image has date in its metadata so the plugin actually shows the date on the statusbar. If the image doesn't have it, the size of the statusbar is normal.

**Comment by NiceandGently** [comment]
@monsta 
Can you send send me an image with a date inside, i don't have one :-/
I quess i need to set the margin in date-plugin too.

**Comment by NiceandGently** [comment]
this is also not need anymore after extra-resize code is removed
https://git.gnome.org/browse/eog/commit/?id=10f17139ed47ebc194ece30e6632ba441463de75

**Comment by NiceandGently** [comment]
Further investigation shows that the date-plugin use GtkStatusbar as widget.
As you can see in second commit i ported the 'num counter' from GtkStatusbar to GtkLabel, which makes it possible to use a margin.
I don't think it's possible to do the same for the date-plugin, because a here a widget with more than one argument is needed.
But
a) eom resize the statusbar also without this PR if the progressbar comes in and date-plugin is enabled.
b) the date plugin isn't enabled as default
c) eog has the same problem if date-plugin is enabled.
So, why not ignoring this?
I mean it's nice to have a small statusbar without date-plugin in gtk3 version.

**Comment by monsta** [comment]
@flexiondotorg: ok, I think it can be merged for now, we can handle the plugin issue later (since this is GTK+3 stuff, no hurry).

**Comment by NiceandGently** [comment]
@stefano-k 
@flexiondotorg 
can please review this PR?
I have another fix for a glib-critical issue, but this PR blocks me to upload the new PR.
Thanks

**Pull request merged**
