### PR TITLE
Next backports 1

### PR DESCRIPTION
**Pull request by raveit65**
This PR do some basic non visual changes, which makes the code more equal to eog.
For making it possible to back port further improvements or bug fixes.
Please test.

### CODE REVIEW

**Comment by lukefromdc** [comment]
I did get this block of odd build warnings both with this PR and with master:
```

eom-exif-util.h:40: Warning: Eom: eom_exif_util_set_label_text: argument exif_data: Unresolved type: 'ExifData*'
eom-exif-util.h:44: Warning: Eom: eom_exif_util_set_focal_length_label_text: argument exif_data: Unresolved type: 'ExifData*'
eom-exif-util.c:286: Warning: Eom: eom_exif_data_get_value: argument exif_data: Unresolved type: 'ExifData*'
eom-exif-util.h:53: Warning: Eom: eom_exif_data_copy: argument data: Unresolved type: 'ExifData*'
eom-exif-util.h:53: Warning: Eom: eom_exif_data_copy: return value: Unresolved type: 'ExifData*'
eom-exif-util.h:54: Warning: Eom: eom_exif_data_free: argument data: Unresolved type: 'ExifData*'
eom-window.h:128: Warning: Eom: eom_window_get_properties_dialog: return value: Missing (transfer) annotation
eom-exif-util.c:286: Warning: Eom: eom_exif_data_get_value: argument exif_data: Unresolved type: 'ExifData*'
eom-exif-util.h:53: Warning: Eom: eom_exif_data_copy: argument data: Unresolved type: 'ExifData*'
eom-exif-util.h:53: Warning: Eom: eom_exif_data_copy: return value: Unresolved type: 'ExifData*'
eom-exif-util.h:54: Warning: Eom: eom_exif_data_free: argument data: Unresolved type: 'ExifData*'


```

**Comment by raveit65** [comment]
Those are gobject-introspecton warnings, not related to PR.

**Comment by raveit65** [comment]
Build with
`./configure --enable-introspection=no`
and they are gone.
I hope i will find some commits in eog to fix that later.......

**Comment by raveit65** [comment]
`eom-window.h:128: Warning: Eom: eom_window_get_properties_dialog: return value: Missing (transfer) annotation` is  fixed.

**Comment by raveit65** [comment]
Yes other PR needs to be merged first.

**Pull request merged**
