### PR TITLE
refactor draw/expose code a bit

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by raveit65** [comment]
how did you test the print-preview?
here eom open always atril or evince.

**Comment by monsta** [comment]
I didn't test it yet :smile:
It's not a fix, just a small refactoring to reduce duplicated code, and I've intended it for the next dev phase (1.13).

As for preview via pdf, it happens even w/o my work. It first tries ```evince```, then gives a ```Gtk-WARNING``` when it can't find it on my system, then tries ```atril``` and opens the generated pdf in it. It's the same in both GTK+ builds.
It might be the default GTK+ behavior when the app doesn't provide its own print preview page (like ```pluma``` does)...

**Comment by monsta** [comment]
Ok, now I've tested it, preview seems to be ok:

eom-print-preview

**Comment by raveit65** [comment]
Dow!
Same here.
The preview button itself is bit misleading if you are on another tab :)
So, the PR can be applied.

**Pull request merged**
