### PR TITLE
enable the sidebar, preparation

### PR DESCRIPTION
**Pull request by raveit65**
I like to split the work for the sidebar in 2 PRs for better review.
The first 2 commits are basically needed for enabling the sidebar, the other ones are resulting commits after the port to GtkApplication.
`
Port EogApplication to GtkApplication ` is really needed otherwise eom won't close any more with the sidebar enabled.
As a result we need to fix https://github.com/mate-desktop/eom/issues/145
to avoid seeing this warnings from libpeas port.

Please test

### CODE REVIEW

**Comment by raveit65** [comment]
PS, for fixing https://github.com/mate-desktop/eom/issues/145 i need really help.

**Comment by vkareh** [comment]
@raveit65 - just noticed that this pr should enable the sidebar entry, but it doesn't on my side... how do I test that part?

**Comment by lukefromdc** [comment]
Segfault came with this backtrace in gdb:

```
Thread 1 "eom" received signal SIGSEGV, Segmentation fault.
0x00007ffff5c3af90 in gtk_container_foreach ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) thread apply all bt full

Thread 11 (Thread 0x7fffe237b700 (LWP 4173)):
#0  0x00007ffff24888f9 in syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff2d91be4 in g_cond_wait_until ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff2d214e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff2d21a7c in g_async_queue_timeout_pop ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff2d74d2e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff2d742c5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff6a915aa in start_thread (arg=0x7fffe237b700)
    at pthread_create.c:463
        pd = 0x7fffe237b700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736988690176, -5232561581368769109, 140737488340494, 140737488340495, 140737488340624, 23, 5232602879212684715, 5232577645434930603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007ffff248dcbf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 5 (Thread 0x7fffe37fe700 (LWP 4067)):
#0  0x00007ffff24835d9 in __GI___poll (fds=0x7fffd000a640, nfds=6, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff2d4d7b1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff2d4db42 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff40dd5f6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff2d742c5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6a915aa in start_thread (arg=0x7fffe37fe700)
    at pthread_create.c:463
        pd = 0x7fffe37fe700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737010198272, -5232561581368769109, 140737100228558, 140737100228559, 140737100228688, 0, 5232604461371262379, 5232577645434930603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff248dcbf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 4 (Thread 0x7fffe3fff700 (LWP 4066)):
#0  0x00007ffff24835d9 in __GI___poll (fds=0x7fffdc0068d0, nfds=2, timeout=2489) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff2d4d7b1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff2d4d8bc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff2d4d901 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff2d742c5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6a915aa in start_thread (arg=0x7fffe3fff700)
    at pthread_create.c:463
        pd = 0x7fffe3fff700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737018590976, -5232561581368769109, 140737100228190, 140737100228191, 140737100228320, 0, 5232605561419761067, 5232577645434930603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff248dcbf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 3 (Thread 0x7fffe8ddb700 (LWP 4065)):
#0  0x00007ffff24835d9 in __GI___poll (fds=0x555555691d50, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff2d4d7b1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff2d4d8bc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffe8de3ccd in  ()
    at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff2d742c5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6a915aa in start_thread (arg=0x7fffe8ddb700)
    at pthread_create.c:463
        pd = 0x7fffe8ddb700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737100232448, -5232561581368769109, 140737488346494, 140737488346495, 140737488346624, 0, 5232590458167264683, 5232577645434930603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff248dcbf in clone ()

    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe97e9700 (LWP 4064)):
#0  0x00007ffff24888f9 in syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff2d91acf in g_cond_wait ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x0000555555594d3b in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:137
#3  0x00007ffff2d742c5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6a915aa in start_thread (arg=0x7fffe97e9700)
    at pthread_create.c:463
        pd = 0x7fffe97e9700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140737110775552, -5232561581368769109, 140737488348430, 140737488348431, 140737488348560, 0, 5232591273137309099, 5232577645434930603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007ffff248dcbf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 1 (Thread 0x7ffff7e8cac0 (LWP 4060)):
#0  0x00007ffff5c3af90 in gtk_container_foreach ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#1  0x00007ffff5c3b21e in gtk_container_get_children ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff5bc590d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff5bc59a2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff5bc59a2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff5bc6a85 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff7eda680 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff2d4d495 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff2d4d838 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff2d4d8bc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff40b13ed in g_application_run ()
    at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x0000555555573571 in main (argc=<optimized out>, argv=<optimized out>)
    at main.c:171
        error = 0x0
        ctx = <optimized out>
        provider = <optimized out>
(gdb)

```

**Comment by lukefromdc** [comment]
With master closing one window exits normally, even with GTK 3.23.0. Only closing a second window segfaults on master

**Comment by lukefromdc** [comment]
The backtrace is similar to in master, save that the offending thread starts in main with  g_application_run () instead of with  g_main_loop_run ()  and occurs now with closing even one out of one window

**Comment by raveit65** [comment]
@raveit65 - just noticed that this pr should enable the sidebar entry, but it doesn't on my side... how do I test that part?

I split the whole PR in 2 for better review, you need to apply https://github.com/mate-desktop/eom/pull/172
, which has all commits.

**Comment by raveit65** [comment]
I googled a lot about this warning
```
Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
```
Best hints i found at https://github.com/GNOME/meld/pull/7
If i understand this correctly than it is more a problem how  an application is closed.
The fix for meld is here, but it is in python.
https://github.com/GNOME/meld/pull/7/commits/044844b73a361572931f953ea9e29e957d595c2d

**Comment by raveit65** [comment]
I moved the fix for the warnings to earlier commit history order, so PR is rebased.

**Pull request merged**
