### PR TITLE
Read authors and documenters (updated) from eom.about gresource

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
I had an issue with `make distcheck`

**Comment by lukefromdc** [comment]
How should people test this?

**Comment by rbuj** [comment]
Open "About Eye of MATE" dialog (choose Help > About menu item), and click on Credits button.

Before:

about-1

After:

about-2

**Comment by rbuj** [comment]
I took the new authors by running the following command:

`git log --pretty="%an <%ae>" --since "2012-01-01" -- . "_.h" "_.c" | sort | uniq`

**Comment by rbuj** [comment]
I didn't add the nicknames in author list to avoid duplicated entries, however I recovered some authors using the [MATE Team](https://mate-desktop.org/team/) web page.

**Comment by sc0w** [comment]
sadly, the mate web page is outdated and seems to be unmaintained...

**Comment by yetist** [comment]
> I had an issue with `make distcheck`

Is that ok now?

**Comment by raveit65** [comment]
@rbuj 
distcheck runs fine here and at travis. Does it run by you?

**Comment by rbuj** [comment]
@raveit65 
I saw that travis reported an error with distcheck. eom.about should be in data (not src) dir and data/Makefile.am (not src/Makefile.am) must include eom.about in EXTRA_DIST.
```
$ git grep GLIB_COMPILE_RESOURCES
configure.ac:AC_PATH_PROG([GLIB_COMPILE_RESOURCES], [glib-compile-resources])
src/Makefile.am:eom_resources_deps = $(shell $(GLIB_COMPILE_RESOURCES) --sourcedir=$(top_srcdir)/data --generate-dependencies $(top_srcdir)/src/eom.gresource.xml)
src/Makefile.am:        $(AM_V_GEN) $(GLIB_COMPILE_RESOURCES) "$<" --target=$@ \
```

**Comment by raveit65** [comment]
@rbuj 
" You saw" means it is is fixed now?

**Comment by raveit65** [comment]
I don't see a error/warning message at travis logs.

**Comment by raveit65** [comment]
And eom.about is in the generated tarball.

**Comment by rbuj** [comment]
Yes, it's fixed now.

**Comment by raveit65** [comment]
An installation from a fresh generated tarball to /usr/local gives me the new authors in about dialog.
And i don't see a eom.about text file under /usr/local/share/, so i assume the resource file works fine, or not?

**Comment by rbuj** [comment]
Can I add update-authors.pl?

Script to update Authors value:

```perl
#!/usr/bin/perl
=pod

    update-authors.pl is part of Eye of MATE.

    Eye of MATE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    Eye of MATE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Eye of MATE.  If not, see <http://www.gnu.org/licenses/>.

=cut
use strict;
use warnings;

sub GetCurrentAuthors {
  my @authors;
  open(FILE,"data/eom.about") or die "Can't open data/eom.about";
  while (<FILE>) {
    if (/^Authors=*(.+)$/) {
      @authors=split(";",$1);
    }
  }
  close FILE;
  return @authors;
}

sub GetNewAuthors {
  my @authors = `git log --pretty="%an <%ae>" --since "2012-01-01" -- . "_.h" "_.c" | sort | uniq | sed 's/@/%/g' | sed '/^mate-i18n.*/d'`;
  chomp @authors;
  $_ eq 'hekel <hekel%archlinux.info>' and $_ = 'Adam Erdman <hekel%archlinux.info>' for @authors;
  $_ eq 'Martin Wimpress <code%flexion.org>' and $_ = 'Martin Wimpress <martin%mate-desktop.org>' for @authors;
  $_ eq 'monsta <monsta%inbox.ru>' and $_ = 'Vlad Orlov <monsta%inbox.ru>' for @authors;
  $_ eq 'Monsta <monsta%inbox.ru>' and $_ = 'Vlad Orlov <monsta%inbox.ru>' for @authors;
  $_ eq 'raveit65 <chat-to-me%raveit.de>' and $_ = 'Wolfgang Ulbrich <mate%raveit.de>' for @authors;
  $_ eq 'raveit65 <mate%raveit.de>' and $_ = 'Wolfgang Ulbrich <mate%raveit.de>' for @authors;
  $_ eq 'rbuj <robert.buj%gmail.com>' and $_ = 'Robert Buj <robert.buj%gmail.com>' for @authors;
  $_ eq 'Scott Balneaves <sbalneav%ltsp.org>' and $_ = 'Scott Balneaves <sbalneav%mate-desktop.org>' for @authors;
  $_ eq 'Wolfgang Ulbrich <chat-to-me%raveit.de>' and $_ = 'Wolfgang Ulbrich <mate%raveit.de>' for @authors;
  return @authors;
}

my @A = GetCurrentAuthors;
my @B = GetNewAuthors;
my @merged = sort { $a cmp $b } keys %{{map {($_ => 1)} (@A, @B)}};
print join(';',@merged) . ';';
```
Human readable text
```
./update-authors.pl | tr ';' '\n'
```

**Comment by sc0w** [comment]
@rbuj 

I don't know if this is possible in that script but, I think better algorithm is: 

- if one mail have different authors, use the latest author (seeing the last commit date)

- if one author have different mails, use the latest mail (seeing the last commit date)

This avoid to modify manually a lot of times in the future

**Comment by yetist** [comment]
I agree with your idea, we can write a script to save in mate-dev-scripts, run it for each repos before the release of the version to generate the about file.

**Pull request merged**
