### PR TITLE
[1.8] don't change file permissions when saving the modified image

### PR DESCRIPTION
**Pull request by monsta**
adapted from:
https://git.gnome.org/browse/eog/commit/?id=4626596c2c179bfe35c4212efced15c38d7337d6

### CODE REVIEW

**Comment by sc0w** [comment]
hello @monsta , I like to apply this to jessie (I am a new Debian MATE team member)

but, this doesn't work as expected, I think

my tests:

-----------------------------------------------------------------------------------------

**permissions**

eog 3.20.5
0666 -> rotate save and quit -> 0666
0400 -> rotate save and quit -> 0400 and eog can't save the image with same name

eom 1.16.0
0666 -> rotate save and quit -> 0666
0400 -> rotate save and quit -> 0400 and eom can't save the image (read only, the expected, I think)

eom 1.8.0 (jessie)
**0666** -> rotate save and quit -> **0600**
**0400** -> rotate save and quit -> **0600** and **eom saves the image**

eom jessie with the patch
0666 -> rotate save and quit -> 0666
**0400** -> rotate save and quit -> **0600** and **eom saves the image**

eom jessie with the patch with the two lines `mode_mask` commented
0666 -> rotate save and quit -> 0666
0400 -> rotate save and quit -> 0400 and **eom saves the image**

**groupid**

with eog 3.20.5, eom 1.16, 1.8 (jessie), and 1.8 with the patch, the same behaviour: **eog and eom overwrite the group id** (if the file has user:anotheruser eom overwrites it to user:user)

-------------------------------------------------------------

so, what do you think about this?

I will apply the patch with the two lines commented?

**Comment by monsta** [comment]
Hmm, that's weird. 

> eom jessie with the patch with the two lines mode_mask commented
0666 -> rotate save and quit -> 0666
0400 -> rotate save and quit -> 0400 and eom saves the image

How can it save the image with 0400?

**Comment by sc0w** [comment]
yes, weird, I don't know why, but it happens

**Comment by monsta** [comment]
Hmm I don't get it... my tests with eom 1.16 and 1.18 in Stretch show that it saves the image with 0400 just fine, modifying the attributes to 0600. Before I tested it, I thought it should keep 0400 and therefore don't save the image.

**Pull request merged**
