### PR TITLE
Update FSF address

### PR DESCRIPTION
**Pull request by tamplan**
Update [FSF address](https://www.fsf.org/about/contact/)

### CODE REVIEW

**Comment by rbuj** [comment]
Fix old mail postcode and address:
https://github.com/mate-desktop/eom/blob/0f2a84776341a31c3bf03787a246d3a379db504d/src/eom-application-internal.h#L22

**Comment by raveit65** [comment]
There is a old address left at eom/src/eom-application-internal.h

**Comment by tamplan** [comment]
i have try to squash 2 commits with command line...

**Comment by raveit65** [comment]
> i have try to squash 2 commits with command line...

... and it works excellent :)

**Pull request merged**
