### PR TITLE
Fix display of SVG images

### PR DESCRIPTION
**Pull request by lukefromdc**
Disable double buffering as it causes .svg images to render well above the view, often to the point that they only appear at all on zooming in. Note that this reverts 

mate-desktop@9c5a19a

and modifies the comment in the code to reflect why this line had to be brought back

### CODE REVIEW

**Comment by monsta** [comment]
Hmm... are you sure? The upstream [commit](https://git.gnome.org/browse/eog/commit/?id=f0410a55778e719da8f2b62f0e5060bb128f028e) where we took this from says:

> Enabling double-buffer fixes the flickering and the slowness with huge images.

And they never added that line back...

**Comment by lukefromdc** [comment]
How huge are we talking about? I never once saw that, and I do need 
svg support.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/eom/issues/117 includes screenshots of what enabling double buffering does to SVG display on my systems. Maybe this is another gtk3.19 issue?

**Comment by lukefromdc** [comment]
Closing this in favor of 
https://github.com/mate-desktop/eom/pull/118
which does the same job without disabling double buffering

**Pull request closed without merging**
