### PR TITLE
Add eom-thumbnailer for webp files

### PR DESCRIPTION
**Pull request by rbuj**
```shell
$ exiftool ~/.cache/thumbnails/normal/*.png
<cut>
======== /home/robert/.cache/thumbnails/normal/fe4fb554664b67fc6c8e33157fa9c88e.png
ExifTool Version Number         : 11.70
File Name                       : fe4fb554664b67fc6c8e33157fa9c88e.png
Directory                       : /home/robert/.cache/thumbnails/normal
File Size                       : 20 kB
File Modification Date/Time     : 2020:01:21 18:49:11+01:00
File Access Date/Time           : 2020:01:21 18:49:11+01:00
File Inode Change Date/Time     : 2020:01:21 18:49:11+01:00
File Permissions                : rw-------
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 128
Image Height                    : 86
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Significant Bits                : 8 8 8
Thumb URI                       : file:///home/robert/Baixades/1.webp
Thumb M Time                    : 1461208642
Software                        : MATE::ThumbnailFactory
Image Size                      : 128x86
Megapixels                      : 0.011
    8 image files read
```
Webp thumbnail on eom's image collection list
Captura de pantalla a 2020-01-21 18-53-58

Webp thumbnail on Caja's icon view
Captura de pantalla a 2020-01-21 18-55-28

### CODE REVIEW

**Comment by raveit65** [comment]
It helps to check travis builds. Build for Archlinux failed.
```
/configure: line 14445: glib-2.0: command not found

checking for THUMBNAILER... no

configure: error: Package requirements (

	glib-2.0 >= 2.52.0

	gio-2.0 >= 2.52.0

        MagickWand

) were not met:

Package 'MagickWand', required by 'virtual:world', not found
```
Sadly, the log doesn't show if `libmagick6`is really installed.
But it seems to be the right dependency 
https://www.archlinux.org/packages/extra/x86_64/libmagick6/
```
usr/include/ImageMagick-6/wand/magick-wand.h
usr/include/ImageMagick-6/wand/magick_wand.h
```

**Comment by raveit65** [comment]
I fedora the include is different, maybe this is the problem?
/usr/include/ImageMagick-6/wand/MagickWand.h
ArchLinux:
usr/include/ImageMagick-6/wand/magick-wand.h
usr/include/ImageMagick-6/wand/magick_wand.h

**Comment by raveit65** [comment]
Do i have to restart session?
Bildschirmfoto zu 2020-01-25 16-37-37

**Comment by rbuj** [comment]
Test:
- update mime database
```sudo update-mime-database /usr/share/mime```
- close all caja windows
```killall -9 caja```
- clear thumbnails cache
```rm -fr ~/.cache/thumbnails```
- log out and login to the desktop
```sudo systemctl restart lightdm.service```

**Comment by rbuj** [comment]
You can also create image thumbnail from command line:
```$ eom-thumbnailer input.webp output.png```

**Comment by raveit65** [comment]
Session restart did the trick. Now i see a thumbnail in caja or in eom gallerie for webp files.
Now we need only to find out why it doesn't build for ArchLinux.
And we have some build warnings.
https://travis-ci.org/mate-desktop/eom/jobs/641125146#L3059
```
eom-thumbnailer.c:161:3: warning: Value stored to 'magick_wand' is never read

                magick_wand = DestroyMagickWand (magick_wand);

                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

eom-thumbnailer.c:174:3: warning: Value stored to 'magick_wand' is never read

                magick_wand = DestroyMagickWand (magick_wand);

                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rbuj** [comment]
@raveit65 done

**Comment by cwendling** [comment]
@rbuj if EOM loads the webp, that suggests there is a gdk-pixbuf loader for it, isn't it?  (there is https://github.com/aruiz/webp-pixbuf-loader in any case)
If so, do we really need an extra ImageMagick code for that (with its own security issues), or can't the regular thumbnailer take advantage of this loader?

If this is a silly question, please disregard, I might not be up-to-date with current thumbnailing mechanism.

**Comment by rbuj** [comment]
@cwendling If you want to use gdk-pixbuf for creating the thumbnails of the webp files, then you just need to add `image/webp` in MimeType list on /usr/share/thumbnailers/gdk-pixbuf file:
```
$ cat /usr/share/thumbnailers/gdk-pixbuf:
thumbnailer.thumbnailer 
[Thumbnailer Entry]
TryExec=/usr/bin/gdk-pixbuf-thumbnailer
Exec=/usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
MimeType=image/png;image/bmp;image/x-bmp;image/x-MS-bmp;image/gif;image/x-icon;image/x-ico;image/x-win-bitmap;image/vnd.microsoft.icon;application/ico;image/ico;image/icon;text/ico;application/x-navi-animation;image/jpeg;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/tiff;image/x-xpixmap;image/x-xbitmap;image/x-tga;image/x-icns;image/jp2;image/jpeg2000;image/jpx;image/x-quicktime;image/qtif;image/webp;
```
Or create  /usr/share/thumbnailers/webp-gdk-pixbuf file:
```
[Thumbnailer Entry]
TryExec=/usr/bin/gdk-pixbuf-thumbnailer
Exec=/usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
MimeType=image/webp;
```
Test
```shell
$ gdk-pixbuf-thumbnailer ~/Imatges/1.webp thumb.png 
```

**Comment by rbuj** [comment]
@raveit65 @mate-desktop/core-team 

We can also add the option `--with-gdk-pixbuf-thumbnailer=FILEPATH/system/[]`, making optional the eom-thumbnailer binary.  Available options for `--with-gdk-pixbuf-thumbnailer`:
- FILEPATH : path to gdk-pixbuf-thumbnailer file
- system : for getting the path to system's gdk-pixbuf-thumbnailer file)
- [] : eom-thumbnailer binary

If you agree, we can do it in a separate PR.

**Comment by rbuj** [comment]
bench.sh
```shell
#!/bin/bash -x
export LC_ALL=C.UTF-8

wget -q https://www.gstatic.com/webp/gallery/1.webp
time gdk-pixbuf-thumbnailer 1.webp gdk-pixbuf-thumbnailer.png
time eom-thumbnailer 1.webp eom-thumbnailer.png
file *.png
ls -la *.png
```
Output:
```shell
+ export LC_ALL=C.UTF-8
+ LC_ALL=C.UTF-8
+ wget -q https://www.gstatic.com/webp/gallery/1.webp
+ gdk-pixbuf-thumbnailer 1.webp gdk-pixbuf-thumbnailer.png

real	0m0.022s
user	0m0.020s
sys	0m0.001s
+ eom-thumbnailer 1.webp eom-thumbnailer.png

real	0m0.044s
user	0m0.052s
sys	0m0.009s
+ file eom-thumbnailer.png gdk-pixbuf-thumbnailer.png
eom-thumbnailer.png:        PNG image data, 256 x 171, 8-bit/color RGBA, non-interlaced
gdk-pixbuf-thumbnailer.png: PNG image data, 256 x 171, 8-bit/color RGB, non-interlaced
+ ls -la eom-thumbnailer.png gdk-pixbuf-thumbnailer.png
-rw-rw-r--. 1 robert robert 88083 Jan 28 12:56 eom-thumbnailer.png
-rw-rw-r--. 1 robert robert 74078 Jan 28 12:56 gdk-pixbuf-thumbnailer.png
```

**Comment by raveit65** [comment]
I agree with adding --with-gdk-pixbuf-thumbnailer option, to make people happy who prefer a slower thumbnailer :lollipop:

**Comment by cwendling** [comment]
> I agree with adding --with-gdk-pixbuf-thumbnailer option, to make people happy who prefer a slower thumbnailer 

?  From @rbuj's data, the gdk-pixbuf one is *way* faster (between 2 to 3 times), and it produces a smaller thumbnail file.  Assuming both results are correct enough for a thumbnail, the gdk-pixbuf one "wins".

IMO we should not add image reading code that do not provide new functionality, because there is always a million security issues with those, and a thumbnailer is even more sensitive to those as it's more or less ran behind the user's back.

IMHO, what should be done is one of:
* nothing, and let the installation of the WebP GdkPixbuf loader provide the MIME association required
* provide the required MIME association ourselves because it's missing.

Again, AIUI we *need* the WebP GdkPixbuf loader for openinnig those images in EOM *anyway*, so I'm not seeing the point of adding an additional loader here.

But that's just my 2¢, FWIW :slightly_smiling_face:

**Comment by rbuj** [comment]
@raveit65 @cwendling done.

to use gdk-pixbuf-thumbnailer:
```shell
$ ./configure --prefix=/usr && make
```
to use eom-thumbnailer:
```shell
$ ./configure --prefix=/usr --without-gdk-pixbuf-thumbnailer && make
```

**Comment by raveit65** [comment]
> ? From @rbuj's data, the gdk-pixbuf one is way faster (between 2 to 3 times), and it produces a smaller thumbnail file. Assuming both results are correct enough for a thumbnail, the gdk-pixbuf one "wins".

Ok, i was wrong

In this case i don't get what the advantage is to use eom-thumbnailer without gdk-pixbuf ?

**Comment by rbuj** [comment]
I don't care about the difference in the obtained results, since I see them similar and they use the same libwebp library. The time spent depends on the [method for scaling / image quality](https://en.wikipedia.org/wiki/Comparison_gallery_of_image_scaling_algorithms), such as the size where a different number of channels is used. In both cases the resulting image is optimized for rendering in web browsers.
```shell
[robert@localhost ~]$ rpm -q --requires ImageMagick-libs | grep libwebp
libwebp.so.7()(64bit)
libwebpdemux.so.2()(64bit)
libwebpmux.so.3()(64bit)
[robert@localhost ~]$ rpm -q --requires webp-pixbuf-loader | grep libwebp
libwebp.so.7()(64bit)
```

**Comment by rbuj** [comment]
bench.sh
```shell
#!/bin/bash -x
export LC_ALL=C.UTF-8
# https://en.wikipedia.org/wiki/Lenna#/media/File:Lenna_(test_image).png
time gdk-pixbuf-thumbnailer -s 128 'Lenna_(test_image).png' gdk-pixbuf-thumbnailer.png
time eom-thumbnailer -s 128 'Lenna_(test_image).png' eom-thumbnailer.png
file *.png
ls -la *.png
```
output
```shell
+ export LC_ALL=C.UTF-8
+ LC_ALL=C.UTF-8
+ gdk-pixbuf-thumbnailer -s 128 'Lenna_(test_image).png' gdk-pixbuf-thumbnailer.png

real	0m0.024s
user	0m0.014s
sys	0m0.008s
+ eom-thumbnailer -s 128 'Lenna_(test_image).png' eom-thumbnailer.png

real	0m0.047s
user	0m0.049s
sys	0m0.020s
+ file 'Lenna_(test_image).png' eom-thumbnailer.png gdk-pixbuf-thumbnailer.png
Lenna_(test_image).png:     PNG image data, 512 x 512, 8-bit/color RGB, non-interlaced
eom-thumbnailer.png:        PNG image data, 128 x 128, 8-bit/color RGBA, non-interlaced
gdk-pixbuf-thumbnailer.png: PNG image data, 128 x 128, 8-bit/color RGB, non-interlaced
+ ls -la 'Lenna_(test_image).png' eom-thumbnailer.png gdk-pixbuf-thumbnailer.png
-rw-rw-r--. 1 robert robert 473831 Jan 28 19:28 'Lenna_(test_image).png'
-rw-rw-r--. 1 robert robert  36845 Jan 28 19:36  eom-thumbnailer.png
-rw-rw-r--. 1 robert robert  31075 Jan 28 19:36  gdk-pixbuf-thumbnailer.png
```
### eom-thumbnailer.png

eom-thumbnailer

### gdk-pixbuf-thumbnailer.png

gdk-pixbuf-thumbnailer

### eom scrrenshot zoom x2000

without smooth images when zoom in/out

Captura de pantalla a 2020-01-28 19-31-55

Captura de pantalla a 2020-01-28 19-32-11

**Comment by raveit65** [comment]
@rbuj 
I complete agree with PR

**Comment by b4n** [comment]
While the thumbnail from this code might be slightly sharper (which possibly comes from the gdk-pixbuf one doing partial image load?), I hardly think there is a relevant difference here.  We're talking about *thumbnails* here, thus the result should convey a good idea of what the image looks like, but it doesn't have to be the best possible scaledown of the original image.

I still stand with my opinion that we shouldn't add this kind of code without a *great* reason because of how sensible it is.

**Comment by cwendling** [comment]
Oops, that was me above

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Any other opinion , thoughts?

**Comment by rbuj** [comment]
I have not been able to build mate-terminal, caja, mate-control-center using gcc on Fedora rawhide.
global variable -> object instance ?

**Comment by lukefromdc** [comment]
Personally, I have never even seen a webp file that I know of, but I have a rather limited workflow.That said, we don't want people finding they can't open their image files in EOM, and ideally anything that opens would also thumbnail. We also don't want the thumbnail code heavy enough to cause EOM to bog down on opening a large directory with thumbnails enabled.

**Comment by raveit65** [comment]
> I still stand with my opinion that we shouldn't add this kind of code without a great reason because of how sensible it is.

Why this is sensible?
Any reason not to do that?
Atril has also  a thumbnailer.

@rbuj 
Can we make the thumbnailer optional with 2 options?
1. --compile-with-thumloader
2. --without-gdk-pixbuf-thumbnailer

Than people have the freedom of choice

**Comment by b4n** [comment]
> Why this is sensible?

Because it is reading random images from untrusted sources, and this has a forever-growing history of security vulnerabilities.

My concern is that this PR *adds* a new image parsing code path, so if you open a malicious WebP file, it will be read by 2 different, possibly buggy, code paths, widening the sensitive surface area.  And the fact that it might partially use the same library in the end only makes this *less bad*, but not really better: they are not directly using the same library, and even if they were there could be bugs in the calls.

My secondary concern is duplicating of functionality: @rbuj shown a way with mere configuration to use the loader that is already used if you want EOM to actually open your WebP file, so why would we need another loader?  We do not *need* a EOM-specific thumbnailer, and we do not *need* an addionnal loader.

**Comment by raveit65** [comment]
> Because it is reading random images from untrusted sources

No, it reads images from a local machine and not from a website.
It is in your responsibility to download images (every format) from the www or not.
And my box is per definition a trusted source for me.

> so why would we need another loader? We do not need a EOM-specific thumbnailer, and we do not need an addionnal loader.

This is your personal opinion.

Anyway, with a config option you're not forced to install it.
So, why you want to force other people like me not to install a very useful and excellent feature?

**Comment by b4n** [comment]
> > Because it is reading random images from untrusted sources
> 
> No, it reads images from a local machine and not from a website.
> It is in your responsibility to download images (every format) from the www or not.
> And my box is per definition a trusted source for me.

I know this is for local files, and it's good for you that you trust every single file on your computer, but I don't think we can expect this from all users.  People will get files from USB sticks, emails, web or wherenot.  And they rightfully don't expect an image to hack their computer -- they just don't know better.

> > so why would we need another loader? We do not *need* a EOM-specific thumbnailer, and we do not *need* an addionnal loader.
> 
> This is your personal opinion.

No, it's not.  The fact is that there is another one that works, and can be used to actually open the images as well.  We can choose not to use it for thumbnailing, but we do not *have* to have our own for the preview to work.  That's part of my point: the C code in this PR is not really needed to be able to thumbnail WebP files: there is another existing working solution.

> Anyway, with a config option you're not forced to install it.
> So, why you want to force other people like me not to install a very useful and excellent feature?

I don't want to force anybody to anything.  But I want you to realize that this code is redundant, and that *any* instance of such code is a potential security hole.  Having two (one for thumbnailing and one for EOM opening the image) is not required and doubles the risk -- and the code to maintain.  And remember that this code will *not* allow you to *open* the image in EOM, it will only allow thumbnailing it.  OTOH, the gdk-pixbuf loader I mentioned allows both (once the configuration for thumbnailing is set up).

I think I'll stop here because I don't have much to add, I'm just paraphrasing myself.  I have given my opinion and concerns, and it's not for me to veto anything.
I just wish the selected solution for thumbnailing WebP file is to use the existing gdk-pixbuf-thumbnailer, possibly adding the relevant configuration file @rbuj [mentioned in a comment](https://github.com/mate-desktop/eom/pull/253#issuecomment-579194371) to get an out-of-the-box experience.

**Comment by rbuj** [comment]
You can disable thumbnails for WebP files by adding `image/webp` in disable list, or if you prefer, disable all external thumbnailers.

Screenshot at 2020-02-01 22-20-18

**Comment by rbuj** [comment]
### Without Thumbnailer
```shell
$ ./autogen.sh --prefix=/usr
<cut>
Configure summary:

	Source code location .......:  .
	Compiler ...................:  gcc
	Extra Compiler Warnings ....:  -Wall -Wmissing-prototypes

	EXIF support ...............:  yes
	XMP support ................:  yes
	JPEG support ...............:  yes
	RSVG support ...............:  yes
	Colour management support ..:  yes
	GObject Introspection.......:  yes
	Thumbnailer.................:  no

Now type `make' to compile eom
```
### Pixbuf Thumbnailer
```shell
$ ./autogen.sh --prefix=/usr --enable-thumbnailer
<cut>
Configure summary:

	Source code location .......:  .
	Compiler ...................:  gcc
	Extra Compiler Warnings ....:  -Wall -Wmissing-prototypes

	EXIF support ...............:  yes
	XMP support ................:  yes
	JPEG support ...............:  yes
	RSVG support ...............:  yes
	Colour management support ..:  yes
	GObject Introspection.......:  yes
	Thumbnailer.................:  /usr/bin/gdk-pixbuf-thumbnailer

Now type `make' to compile eom
```
### IM Thumbnailer
```
$ ./autogen.sh --prefix=/usr --enable-thumbnailer --without-gdk-pixbuf-thumbnailer
<cut>
Configure summary:

	Source code location .......:  .
	Compiler ...................:  gcc
	Extra Compiler Warnings ....:  -Wall -Wmissing-prototypes

	EXIF support ...............:  yes
	XMP support ................:  yes
	JPEG support ...............:  yes
	RSVG support ...............:  yes
	Colour management support ..:  yes
	GObject Introspection.......:  yes
	Thumbnailer.................:  eom-thumbnailer

Now type `make' to compile eom
```

**Pull request merged**
