### PR TITLE
Sidebar and more

### PR DESCRIPTION
**Pull request by raveit65**
This is the second part for enable the sidebar.
The first commits are already submitted in other PR.
https://github.com/mate-desktop/eom/pull/171
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
Yes, disable the reload plugin stops the warning, see https://github.com/mate-desktop/eom/issues/145#issuecomment-300796557

**Comment by raveit65** [comment]
I moved the fix for the warnings to earlier commit history order, so PR is rebased.

**Comment by raveit65** [comment]
One question guys, do you like that the sidebar is at the right side in the window, like in eog?
Or should i move the sidebar back to the left side, which is more a traditional place of a sidebar.
Commit is small and simple.

**Comment by lukefromdc** [comment]
I also prefer the left side

**Comment by raveit65** [comment]
Done, sidebar is on the left side again, PR is rebased.

**Pull request merged**
