### PR TITLE
meson: explicit dep on -lm as required for Fedora35

### PR DESCRIPTION
**Pull request by whatdoineed2do**

### CODE REVIEW

**Comment by raveit65** [comment]
Fedora 35 reached EOL in 2022-12-13.
https://docs.fedoraproject.org/en-US/releases/eol/
Building official packages for EOL releases isn't possible anymore.
So why should we support fedora 35?

**Comment by whatdoineed2do** [comment]
To support legacy users building from source rather than for the distro

Why punish users on EOL installation if they take from git repo?

**Comment by lukefromdc** [comment]
With only Debian based setups here and no landline to download multi-GB installers, I have no way of actually testing something on Fedora

**Comment by whatdoineed2do** [comment]
The material change results in explicit '-lm' being added to the LINK_ARG

This is needed because of the use of pow() in the eom code.

Im guessing something else is explicitly including the system math lib as a dep in newer distro.

**Review by cwendling — APPROVED** [review]
LGTM and works fine, and linking to libm is required on (most) Linux when using stuff from it, like `ceil()`, `log10()`, `pow()`, etc.  We do that in Autotools, and should do it with Meson as well.  This looks like the [recommended way to do it](https://mesonbuild.com/howtox.html#add-math-library-lm-portably), so that's good.

**Comment by cwendling** [comment]
This indeed doesn't seem necessary on my machines, but the changes themselves look good and don't break anything.
As said in the review, linking to *libm* is actually *required* when using any of its features (unless the compiler itself implements it in its builtin lib, but there's no guarantee) if it's not part of *libc* (which it isn't with glibc, at least not currently).  If it works, it's likely because we have a dependency bringing `libm` to the link flags, but we shouldn't depend on this.
As said as well, this is also [done in Autotools](https://github.com/mate-desktop/eom/blob/master/configure.ac#L384), so there definitely is a lot of testing that at least linking to it doesn't *harm* anything :slightly_smiling_face:

**Comment by cwendling** [comment]
Last note: no, I didn't test on Fedora 35, but it doesn't really matter IMO:
- it's unsupported
- the changes themselves are good, whether or not they fix build on Fedora 35
- I'm gonna trust the OP that it does help there

**Comment by zhuyaliang** [comment]
Other dependencies will indirectly depend on libm and libpthread. We have internally used mathematical libraries, which can make libm a necessary dependency

**Review by zhuyaliang — APPROVED** [review]

**Pull request merged**
